<div class="col-span-12">
<form method="post" class="w-full max-w-sm mx-auto">
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="taskName">
                    Nom de la tasca
                </label>
            </div>
            <div class="md:w-2/3">
                <input type="text" name="taskName" class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500" >
            </div>
        </div>
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="user">
                    Nom d'usuari
                </label>
            </div>
            <div class="md:w-2/3">
                <input  type="text" name="user" class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500">
            </div>
        </div>
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="status">
                    Estat
                </label>
            </div>
            <div class="md:w-2/3">
                <select name="status" class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
                    <option value="Per iniciar" 
                        >Per iniciar</option>
                    <option value="En curs"  
                        >En curs</option>
                    <option value="Completat"  
                        >Completat</option>
                </select>
            </div>
        </div>
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="timeStart">
                    Data d'inici
                </label>
            </div>
            <div class="md:w-2/3">
                <div class="flex items-center justify-center">
                    <input name="timeStart" type="date" />
                </div>
            </div>
        </div>
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="timeEnd">
                    Data de fi
                </label>
            </div>
            <div class="md:w-2/3">
                <div class="flex items-center justify-center">
                    <input name="timeEnd" type="date" />
                </div>
            </div>
        </div>
        <div class="md:flex md:items-center">
            <div class="md:w-1/3">
            </div>
            <div class="md:w-2/3">
                <input class="shadow bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="submit">
                </input>
            </div>
        </div>
    </form>
    <div class="grid grid-cols-5">
        <a href="index">
        <button title="Enrere" class="shadow bg-gray-500 hover:bg-gray-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="button">
        <i class="fa-solid fa-chevron-left"></i>
        </button>
        </a>
    </div>
</div>
