Benvingut a l'app.

Això és l'inici.

<div class="container mx-auto mt-5 text-center">


<div class="grid grid-cols-12 gap-4 my-2">
    <div class="bg-red-400 col-span-3">a</div>
    <div class="bg-blue-400 col-span-3">b</div>
    <div class="bg-yellow-400 col-span-3">c</div>
    <div class="bg-green-400 col-span-3 col-end-4">d</div>
</div>

<div class="grid grid-rows-4 gap-4">
    <div class="bg-red-400 row-span-2">a</div>
    <div class="bg-blue-400">b</div>
    <div class="bg-yellow-400">c</div>
    <div class="bg-green-400">d</div>
</div>

</div>